export default {
  namespace: "auth",

  /**
   * Actions and Mutations
   */

  AUTH_LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILURE: "AUTH_LOGIN_FAILURE",

  AUTH_LOGOUT_REQUEST: "AUTH_LOGOUT_REQUEST",
  AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  AUTH_LOGOUT_FAILURE: "AUTH_LOGOUT_FAILURE",

  AUTH_CHECK_REQUEST: "AUTH_CHECK_REQUEST",
  AUTH_CHECK_SUCCESS: "AUTH_CHECK_SUCCESS",
  AUTH_CHECK_FAILURE: "AUTH_CHECK_FAILURE",

  AUTH_GET_OPERATION_REQUEST: "AUTH_GET_OPERATION_REQUEST",
  AUTH_GET_OPERATION_SUCCESS: "AUTH_GET_OPERATION_SUCCESS",
  AUTH_GET_OPERATION_FAILURE: "AUTH_GET_OPERATION_FAILURE",

  AUTH_SET_IS_AUTHENTICATED: "AUTH_SET_IS_AUTHENTICATED",

  /**
   * Getters
   */

  AUTH_GET_USER: "AUTH_GET_USER",
  AUTH_GET_STATUS: "AUTH_GET_STATUS",
  AUTH_GET_ERROR: "AUTH_GET_ERROR",
  AUTH_IS_AUTHENTICATED: "AUTH_IS_AUTHENTICATED",
  AUTH_GET_OPERATIONS: "AUTH_GET_OPERATIONS",
};
