export const LIST_ROW_NAME_EXPERTVIEW = [
  {
    title: "Headline Figures",
    dataIndex: "headlineFigures",
    key: "headlineFigures",
    rowspan: "8",
    isBold: true,
  },
  {
    title: "Sell out Units",
    dataIndex: "sellOutUnitsTU",
    key: "sellOutUnitsTU",
    isBold: true,
    noneBorder: true,
    reference: "headlineFigures",
  },
  {
    title: "NSV",
    dataIndex: "nsvhf",
    key: "nsvhf",
    isBold: true,
    noneBorder: false,
    reference: "headlineFigures",
  },
  {
    title: "CMA",
    dataIndex: "cmahf",
    key: "cmahf",
    isBold: true,
    noneBorder: false,
    reference: "headlineFigures",
  },
  {
    title: "CMA%",
    dataIndex: "cmaPercentHF",
    key: "cmaPercentHF",
    isBold: true,
    noneBorder: false,
    reference: "headlineFigures",
  },
  {
    title: "Margin Af%",
    dataIndex: "marginAfPercentHF",
    key: "marginAfPercentHF",
    isBold: true,
    noneBorder: false,
    reference: "headlineFigures",
  },
  {
    title: "Banner GM%",
    dataIndex: "bannerGMPercentHF",
    key: "bannerGMPercentHF",
    isBold: true,
    noneBorder: false,
    reference: "headlineFigures",
  },
  {
    title: "Store GM%",
    dataIndex: "storeGMPercentHF",
    key: "storeGMPercentHF",
    isBold: true,
    noneBorder: false,
    reference: "headlineFigures",
  },
  {
    title: "Promo ROI%",
    dataIndex: "promoROIPercentHF",
    key: "promoROIPercentHF",
    isBold: true,
    noneBorder: false,
    reference: "headlineFigures",
  },
  {
    title: "",
    dataIndex: "spaceRow",
    key: "spaceRow",
  },
  {
    title: "Promo Specs",
    dataIndex: "promoSpecs",
    key: "promoSpecs",
    rowspan: "8",
    isBold: true,
  },
  {
    title: "# Weeks",
    dataIndex: "weeksPS",
    key: "weeksPS",
    noneBorder: true,
    isBold: true,
    reference: "promoSpecs",
  },
  {
    title: "Price",
    dataIndex: "pricePS",
    key: "pricePS",
    isBold: true,
    noneBorder: false,
    reference: "promoSpecs",
  },
  {
    title: "Disc %",
    dataIndex: "discPercentPS",
    key: "discPercentPS",
    isFirstChild: true,
    noneBorder: false,
    reference: "promoSpecs",
  },
  {
    title: "Base Units",
    dataIndex: "baseUnitsPS",
    key: "baseUnitsPS",
    isBold: true,
    noneBorder: false,
    reference: "promoSpecs",
  },
  {
    title: "Uplift Units",
    dataIndex: "upliftUnitsPS",
    key: "upliftUnitsPS",
    isBold: true,
    noneBorder: false,
    reference: "promoSpecs",
  },
  {
    title: "Uplift %",
    dataIndex: "upliftPercentPS",
    key: "upliftPercentPS",
    isFirstChild: true,
    noneBorder: false,
    reference: "promoSpecs",
  },
  {
    title: "VOD%",
    dataIndex: "vodPercentPS",
    key: "vodPercentPS",
    isFirstChild: true,
    noneBorder: false,
    reference: "promoSpecs",
  },
  {
    title: "Total Units",
    dataIndex: "totalUnits",
    key: "totalUnits",
    rowspan: "4",
    isBold: true,
  },
  {
    title: "Sell in Units",
    dataIndex: "sellInUnitsTU",
    key: "sellInUnitsTU",
    isBold: true,
    noneBorder: true,
    reference: "totalUnits",
  },
  {
    title: "Inv buy Units",
    dataIndex: "invBuyUnitsTU",
    key: "invBuyUnitsTU",
    isFirstChild: true,
    isRed: true,
    noneBorder: false,
    reference: "totalUnits",
  },
  {
    title: "Sell out Units",
    dataIndex: "sellOutUnitsTU",
    key: "sellOutUnitsTU",
    isBold: true,
    noneBorder: false,
    reference: "totalUnits",
  },
  {
    title: "Financials KHC",
    dataIndex: "financialsKHC",
    key: "financialsKHC",
    rowspan: "22",
    isBold: true,
  },
  {
    title: "LSV",
    dataIndex: "lsvfk",
    key: "lsvfk",
    isBold: true,
    noneBorder: true,
    reference: "financialsKHC",
  },
  {
    title: "Trading Terms & Ullage",
    dataIndex: "tradingTermsAndUllageFK",
    key: "tradingTermsAndUllageFK",
    isFirstChild: true,
    isRed: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "GSV",
    dataIndex: "gsvfk",
    key: "gsvfk",
    isBold: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "Perm OI",
    dataIndex: "permOIFK",
    key: "permOIFK",
    isFirstChild: true,
    isRed: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "Temp OI",
    dataIndex: "tempOIFK",
    key: "tempOIFK",
    isFirstChild: true,
    isRed: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "Invoiced Sales",
    dataIndex: "invoicedSalesFK",
    key: "invoicedSalesFK",
    isBold: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "D&A",
    dataIndex: "dAndAFK",
    key: "dAndAFK",
    isFirstChild: true,
    isRed: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "Rebates",
    dataIndex: "rebatesFK",
    key: "rebatesFK",
    isSecondChild: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "Sell In Deal (exc OI)",
    dataIndex: "sellInDealsFK",
    key: "sellInDealsFK",
    isSecondChild: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "Sell Through Deal (WWD)",
    dataIndex: "sellThroughDealsFK",
    key: "sellThroughDealsFK",
    isSecondChild: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "Sell Out Deal",
    dataIndex: "sellOutDealsFK",
    key: "sellOutDealsFK",
    isSecondChild: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "Base Scan Deal",
    dataIndex: "baseScanDealFK",
    key: "baseScanDealFK",
    isThirdChild: true,
    isBlue: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "Top Up Scan Deal",
    dataIndex: "topUpScanDealFK",
    key: "topUpScanDealFK",
    isThirdChild: true,
    isBlue: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "Handling Fee",
    dataIndex: "handlingFeeFK",
    key: "handlingFeeFK",
    isThirdChild: true,
    isBlue: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "Leaf & Display",
    dataIndex: "leafAndDisplayFK",
    key: "leafAndDisplayFK",
    isSecondChild: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "Coop (Lump)",
    dataIndex: "coopFK",
    key: "coopFK",
    isSecondChild: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "NSV",
    dataIndex: "nsvfk",
    key: "nsvfk",
    isBold: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "COGS",
    dataIndex: "cogsfk",
    key: "cogsfk",
    isFirstChild20: true,
    isRed: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "CMA",
    dataIndex: "cmafk",
    key: "cmafk",
    isBold: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "CDS Fees",
    dataIndex: "cdsFeesFK",
    key: "cdsFeesFK",
    isFirstChild20: true,
    isRed: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "Margin Af",
    dataIndex: "marginAfFK",
    key: "marginAfFK",
    isBold: true,
    noneBorder: false,
    reference: "financialsKHC",
  },
  {
    title: "Profit Pool & Retailer Margin",
    dataIndex: "profitPool&RetailerMargin",
    key: "profitPool&RetailerMargin",
    rowspan: "6",
    isBold: true,
  },
  {
    title: "RSV (ex-GST) $",
    dataIndex: "rsvpr",
    key: "rsvpr",
    isBold: true,
    noneBorder: true,
    reference: "profitPool&RetailerMargin",
  },
  {
    title: "Retailer Net Cost",
    dataIndex: "retailerNetCostPR",
    key: "retailerNetCostPR",
    isFirstChild20: true,
    isRed: true,
    noneBorder: false,
    reference: "profitPool&RetailerMargin",
  },
  {
    title: "Retailer GM $",
    dataIndex: "retailerGMPR",
    key: "retailerGMPR",
    isBold: true,
    noneBorder: false,
    reference: "profitPool&RetailerMargin",
  },
  {
    title: "Store Net Cost",
    dataIndex: "storeNetCostPR",
    key: "storeNetCostPR",
    isFirstChild20: true,
    isRed: true,
    noneBorder: false,
    reference: "profitPool&RetailerMargin",
  },
  {
    title: "Store GM $",
    dataIndex: "storeGMPR",
    key: "storeGMPR",
    isBold: true,
    noneBorder: false,
    reference: "profitPool&RetailerMargin",
  },
  {
    title: "Trade Investment",
    dataIndex: "tradeInvestment",
    key: "tradeInvestment",
    rowspan: "5",
    isBold: true,
  },
  {
    title: "Total Trade Spend",
    dataIndex: "totalTradeSpendTI",
    key: "totalTradeSpendTI",
    isBold: true,
    noneBorder: true,
    reference: "tradeInvestment",
  },
  {
    title: "Trade Spend (Fixed)",
    dataIndex: "tradeSpendFixedTI",
    key: "tradeSpendFixedTI",
    isFirstChild: true,
    isBlue: true,
    noneBorder: false,
    reference: "tradeInvestment",
  },
  {
    title: "Trade Spend (Variable)",
    dataIndex: "tradeSpendVariableTI",
    key: "tradeSpendVariableTI",
    isFirstChild: true,
    isBlue: true,
    noneBorder: false,
    reference: "tradeInvestment",
  },
  {
    title: "Total Trade Investment",
    dataIndex: "totalTradeInvestmentTI",
    key: "totalTradeInvestmentTI",
    isBold: true,
    noneBorder: false,
    reference: "tradeInvestment",
  },

  {
    title: "Retailer Financials per Unit",
    dataIndex: "retailerFinancials",
    key: "retailerFinancials",
    rowspan: "6",
    isBold: true,
  },
  {
    title: "Inv Sales Excl Ullage/Unit",
    dataIndex: "invSalesExclUllagePerUnitRF",
    key: "invSalesExclUllagePerUnitRF",
    isBold: true,
    noneBorder: true,
    reference: "retailerFinancials",
  },
  {
    title: "Invoice Value/Unit",
    dataIndex: "invoiceValuePerUnitRF",
    key: "invoiceValuePerUnitRF",
    isBold: true,
    noneBorder: false,
    reference: "retailerFinancials",
  },
  {
    title: "Upfront NIS/Unit",
    dataIndex: "upfrontNISPerUnitRF",
    key: "upfrontNISPerUnitRF",
    isBold: true,
    noneBorder: false,
    reference: "retailerFinancials",
  },
  {
    title: "Net NIS/Unit",
    dataIndex: "netNISPerUnitRF",
    key: "netNISPerUnitRF",
    isBold: true,
    noneBorder: false,
    reference: "retailerFinancials",
  },
  {
    title: "Net Cost/Unit",
    dataIndex: "netCostPerUnitRF",
    key: "netCostPerUnitRF",
    isBold: true,
    noneBorder: false,
    reference: "retailerFinancials",
  },
  {
    title: "Promo KPIs",
    dataIndex: "promoKPIs",
    key: "promoKPIs",
    rowspan: "6",
    isBold: true,
  },
  {
    title: "iNSV",
    dataIndex: "nsvpk",
    key: "nsvpk",
    isBold: true,
    noneBorder: true,
    reference: "promoKPIs",
  },
  {
    title: "iCMA",
    dataIndex: "cmapk",
    key: "cmapk",
    isBold: true,
    noneBorder: false,
    reference: "promoKPIs",
  },
  {
    title: "iTS",
    dataIndex: "tspk",
    key: "tspk",
    isBold: true,
    noneBorder: false,
    reference: "promoKPIs",
  },
  {
    title: "iRSV",
    dataIndex: "rsvpk",
    key: "rsvpk",
    isBold: true,
    noneBorder: false,
    reference: "promoKPIs",
  },
  {
    title: "iGM",
    dataIndex: "gmpk",
    key: "gmpk",
    isBold: true,
    noneBorder: false,
    reference: "promoKPIs",
  },
];

export const LIST_HEADER_NAME = [
  {
    title: "Shelf Price",
    width: "100px",
    headerBgColor: "#CDD3DB",
    align: "center",
    hidden: false,
  },
  {
    title: "Promo 1",
    width: "100px",
    headerBgColor: "#45DFAB",
    align: "center",
    hidden: false,
  },
  {
    title: "Promo 2",
    width: "100px",
    headerBgColor: "#FF9C6E",
    align: "center",
    hidden: false,
  },
  {
    title: "Promo 3",
    width: "100px",
    headerBgColor: "#B37FEB",
    align: "center",
    hidden: false,
  },
  {
    title: "Promo 4",
    width: "100px",
    headerBgColor: "#FFD666",
    align: "center",
    hidden: true,
  },
  {
    title: "Promo 5",
    width: "100px",
    headerBgColor: "#FF7875",
    align: "center",
    hidden: true,
  },
  {
    title: "Promo 6",
    width: "100px",
    headerBgColor: "#5CDBD3",
    align: "center",
    hidden: true,
  },
  {
    title: "Promo 7",
    width: "100px",
    headerBgColor: "#85A5FF",
    align: "center",
    hidden: true,
  },
  {
    title: "Promo 8",
    width: "100px",
    headerBgColor: "#FF85C0",
    align: "center",
    hidden: true,
  },
  {
    title: "Promo 9",
    width: "100px",
    headerBgColor: "#A0D911",
    align: "center",
    hidden: true,
  },
];

export const LIST_FORMAT_CURRENCY_KEY = [
  "nsvhf",
  "cmahf",
  "pricePS",
  "lsvfk",
  "tradingTermsAndUllageFK",
  "gsvfk",
  "permOIFK",
  "tempOIFK",
  "invoicedSalesFK",
  "dAndAFK",
  "rebatesFK",
  "sellInDealsFK",
  "sellThroughDealsFK",
  "sellOutDealsFK",
  "baseScanDealFK",
  "topUpScanDealFK",
  "handlingFeeFK",
  "leafAndDisplayFK",
  "nsvfk",
  "cogsfk",
  "cmafk",
  "cdsFeesFK",
  "marginAfFK",
  "rsvpr",
  "retailerNetCostPR",
  "retailerGMPR",
  "storeNetCostPR",
  "storeGMPR",
  "totalTradeSpendTI",
  "tradeSpendFixedTI",
  "tradeSpendVariableTI",
  "totalTradeInvestmentTI",
  "invSalesExclUllagePerUnitRF",
  "invoiceValuePerUnitRF",
  "upfrontNISPerUnitRF",
  "netNISPerUnitRF",
  "netCostPerUnitRF",
  "nsvpk",
  "cmapk",
  "tspk",
  "rsvpk",
  "gmpk",
  "coopFK",
  "totalnsvhf",
  "totalcmahf",
  "totalpricePS",
  "totallsvfk",
  "totaltradingTermsAndUllageFK",
  "totalgsvfk",
  "totalpermOIFK",
  "totaltempOIFK",
  "totalinvoicedSalesFK",
  "totaldAndAFK",
  "totalrebatesFK",
  "totalsellInDealsFK",
  "totalsellThroughDealsFK",
  "totalsellOutDealsFK",
  "totalbaseScanDealFK",
  "totaltopUpScanDealFK",
  "totalhandlingFeeFK",
  "totalleafAndDisplayFK",
  "totalnsvfk",
  "totalcogsfk",
  "totalcmafk",
  "totalcdsFeesFK",
  "totalmarginAfFK",
  "totalrsvpr",
  "totalretailerNetCostPR",
  "totalretailerGMPR",
  "totalstoreNetCostPR",
  "totalstoreGMPR",
  "totaltotalTradeSpendTI",
  "totaltradeSpendFixedTI",
  "totaltradeSpendVariableTI",
  "totaltotalTradeInvestmentTI",
  "totalinvSalesExclUllagePerUnitRF",
  "totalinvoiceValuePerUnitRF",
  "totalupfrontNISPerUnitRF",
  "totalnetNISPerUnitRF",
  "totalnetCostPerUnitRF",
  "totalnsvpk",
  "totalcmapk",
  "totaltspk",
  "totalrsvpk",
  "totalgmpk",
  "totalcoopFK",
];

export const LIST_FORMAT_PERCENT_KEY = [
  "cmaPercentHF",
  "marginAfPercentHF",
  "bannerGMPercentHF",
  "storeGMPercentHF",
  "promoROIPercentHF",
  "discPercentPS",
  "upliftPercentPS",
  "vodPercentPS",
  "totalcmaPercentHF",
  "totalmarginAfPercentHF",
  "totalbannerGMPercentHF",
  "totalstoreGMPercentHF",
  "totalpromoROIPercentHF",
  "totaldiscPercentPS",
  "totalupliftPercentPS",
  "totalvodPercentPS",
];

export const LIST_UPPERCASE_KEY = [
  "nsvfk",
  "nsvhf",
  "nsvpk",
  "rsvpk",
  "rsvpr",
  "tspk",
  "gmpk",
  "cogsfk",
  "cmapk",
  "cmahf",
  "cmafk",
  "lsvfk",
  "gsvfk"
];

export const LIST_UPPERCASE_THREE_CHAR_KEY = ["cmaPercentHF", "cdsFeesFK", "vodPercentPS"];

export const LIST_BOLD_SUMMARY_KEY = [
  "nsvhf",
  "cmahf",
  "cmaPercentHF",
  "marginAfPercentHF",
  "bannerGMPercentHF",
  "storeGMPercentHF",
  "promoROIPercentHF",
  "weeksPS",
  "pricePS",
  "baseUnitsPS",
  "upliftUnitsPS",
  "sellInUnitsTU",
  "sellOutUnitsTU",
  "lsvfk",
  "gsvfk",
  "invoicedSalesFK",
  "nsvfk",
  "cmafk",
  "marginAfFK",
  "rsvpr",
  "retailerGMPR",
  "storeGMPR",
  "totalTradeSpendTI",
  "totalTradeInvestmentTI",
  "nsvpk",
  "cmapk",
  "tspk",
  "rsvpk",
  "gmpk",
]
