import numeral from "numeral";

export const QUARTER_LENGTH = 13;

export const SHELF_PRICE_CODE = 1;

export const COLOR_LIST_ENTRY_PRICE = [
  {
    name: "Shelf Price",
    code: "#BFBFC1",
    opacityColor: "#fff",
  },
  { name: "Promo 1", code: "#45DFAB", opacityColor: "rgb(69, 223, 171, 0.2)" },
  { name: "Promo 2", code: "#FF9C6E", opacityColor: "rgb(255, 156, 110, 0.2)" },
  { name: "Promo 3", code: "#B37FEB", opacityColor: "rgb(179, 127, 235, 0.2)" },
  { name: "Promo 4", code: "#FFD666", opacityColor: "rgb(255, 214, 102, 0.2)" },
  { name: "Promo 5", code: "#FF7875", opacityColor: "rgb(255, 120, 117, 0.2)" },
  { name: "Promo 6", code: "#5CDBD3", opacityColor: "rgb(92, 219, 211, 0.2)" },
  { name: "Promo 7", code: "#85A5FF", opacityColor: "rgb(133, 165, 255, 0.2)" },
  { name: "Promo 8", code: "#FF85C0", opacityColor: "rgb(255, 133, 192, 0.2)" },
  { name: "Promo 9", code: "#D3F261", opacityColor: "rgb(211, 242, 97, 0.2)" },
  { name: "Total", code: "#074E94", opacityColor: "rgb(95, 166, 227, 0.2)" },
  { name: "Disable", code: "#EAEDF0", opacityColor: "rgb(234, 237, 240, 0.2)" },
];

export const COLOR_OBJECT_ENTRY_PRICE = {
  ShelfPrice: { code: "#000", opacityColor: "" },
  Promo1: {
    code: "#45DFAB",
    opacityColor: "rgb(69, 223, 171, 0.2)",
    bold: false,
  },
  Promo2: {
    code: "#FF9C6E",
    opacityColor: "rgb(255, 156, 110, 0.2)",
    bold: false,
  },
  Promo3: {
    code: "#B37FEB",
    opacityColor: "rgb(179, 127, 235, 0.2)",
    bold: false,
  },
  Promo4: {
    code: "#FFD666",
    opacityColor: "rgb(255, 214, 102, 0.2)",
    bold: false,
  },
  Promo5: {
    code: "#FF7875",
    opacityColor: "rgb(255, 120, 117, 0.2)",
    bold: false,
  },
  Promo6: {
    code: "#5CDBD3",
    opacityColor: "rgb(92, 219, 211, 0.2)",
    bold: false,
  },
  Promo7: {
    code: "#85A5FF",
    opacityColor: "rgb(133, 165, 255, 0.2)",
    bold: false,
  },
  Promo8: {
    code: "#FF85C0",
    opacityColor: "rgb(255, 133, 192, 0.2)",
    bold: false,
  },
  Promo9: {
    code: "#D3F261",
    opacityColor: "rgb(211, 242, 97, 0.2)",
    bold: false,
  },
  Total: {
    code: "#074E94",
    opacityColor: "rgb(221, 235, 247, 0.2)",
    bold: false,
  },
  OverWrite: { code: "#1b00ff", opacityColor: "#fff", bold: true },
};

export const LIST_ROW_NAME_ENTRY_PRICE = [
  {
    name: "Tactic",
    dataIndex: "tacticName",
    type: "text",
    valid: true,
    disabled: true,
  },
  {
    name: "Price",
    dataIndex: "retailPrice",
    type: "text",
    suffixInput: "$",
    validations: "number|positive|not_equal:0|decimal:12,3",
    numberFormat: "$0,0.00",
    valid: true,
    disabled: true,
  },
  {
    name: "Frequency",
    dataIndex: "frequency",
    type: "text",
    validations: "integer|positive",
    numberFormat: "0,0",
    valid: true,
    disabled: true,
  },
  {
    name: "Redemption Unit",
    dataIndex: "redemptionUnits",
    type: "text",
    valid: true,
    disabled: true,
  },
  {
    name: "Volume Units/Case",
    isBold: true,
    dataIndex: "none",
    type: "none",
  },
  {
    name: "Scan (Week)",
    dataIndex: "scanVolume",
    type: "text",
    canExpand: true,
    validations: "integer|positive|not_equal:0|required",
    numberFormat: "0,0",
    valid: true,
    required: true,
    disabled: false,
  },
  {
    name: "Sellthrough (Week)",
    dataIndex: "sellthroughVolume",
    type: "text",
    canExpand: true,
    validations: "integer|positive|not_equal:0|required",
    numberFormat: "0,0",
    valid: true,
    required: true,
    disabled: false,
  },
  {
    name: "Deals",
    isBold: true,
    dataIndex: "none",
    type: "none",
  },
  {
    name: "Off Invoice",
    dataIndex: "offInvoice",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0.00",
    valid: true,
    disabled: true,
  },
  {
    name: "Margin Support",
    dataIndex: "marginSupport",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0.00",
    valid: true,
    disabled: true,
  },
  {
    name: "Case Deal %",
    dataIndex: "caseDealPercent",
    type: "text",
    suffixInput: "%",
    validations: "number|min_value:0|max_value:100",
    numberFormat: "0.0000%",
    valid: true,
    disabled: true,
  },
  {
    name: "Case Deal / SGTT",
    dataIndex: "caseDealSGTT",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0.00",
    valid: true,
    disabled: true,
  },
  {
    name: "WWD",
    dataIndex: "wwd",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0.00",
    valid: true,
    disabled: true,
  },
  {
    name: "Base Scan Deal",
    dataIndex: "baseScanDeal",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0.00",
    valid: true,
    disabled: true,
  },
  {
    name: "Top Up Scan Deal",
    dataIndex: "topUpScanDeal",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0.00",
    valid: true,
    disabled: true,
  },
  {
    name: "Redemption %",
    dataIndex: "redemptionPercent",
    type: "text",
    suffixInput: "%",
    validations: "number|min_value:0|max_value:100",
    numberFormat: "0.0%",
    valid: true,
    disabled: true,
  },
  {
    name: "Coop Display (Lump)",
    dataIndex: "coopDisplay",
    type: "text",
    valid: true,
    disabled: true,
  },
  {
    name: "Financials per Unit/Case",
    isBold: true,
    dataIndex: "none",
    type: "none",
  },
  {
    name: "Invoice Value",
    dataIndex: "invoiceValue",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0.00",
    valid: true,
    disabled: true,
  },
  {
    name: "Upfront NIS",
    dataIndex: "upfrontNIS",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0.00",
    valid: true,
    disabled: true,
  },
  {
    name: "Net NIS",
    dataIndex: "netNIS",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0.00",
    valid: true,
    disabled: true,
  },
  {
    name: "NSV",
    dataIndex: "nsvfpu",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0.00",
    valid: true,
    disabled: true,
  },
  {
    name: "KHC Financials",
    isBold: true,
    dataIndex: "none",
    type: "none",
  },
  {
    name: "LSV",
    dataIndex: "lsv",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0",
    valid: true,
    disabled: true,
  },
  {
    name: "Trade Spend",
    dataIndex: "tradeSpend",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0",
    valid: true,
    disabled: true,
  },
  {
    name: "NSV",
    dataIndex: "nsvkf",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0",
    valid: true,
    disabled: true,
  },
  {
    name: "CMA",
    dataIndex: "cma",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0",
    valid: true,
    disabled: true,
  },
  {
    name: "CMA%",
    dataIndex: "cmaPercent",
    type: "text",
    suffixInput: "%",
    validations: "number|min_value:0|max_value:100",
    numberFormat: "0.0%",
    valid: true,
    disabled: true,
  },
  {
    name: "Retailer Financials",
    isBold: true,
    dataIndex: "none",
    type: "none",
  },
  {
    name: "RSV (excl GST)",
    dataIndex: "rsv",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0",
    valid: true,
    disabled: true,
  },
  {
    name: "Banner GM",
    dataIndex: "bannerGM",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0",
    valid: true,
    disabled: true,
  },
  {
    name: "Banner GM %",
    dataIndex: "bannerGMPercent",
    type: "text",
    suffixInput: "%",
    validations: "number|min_value:0|max_value:100",
    numberFormat: "0.0%",
    valid: true,
    disabled: true,
  },
  {
    name: "Store GM",
    dataIndex: "storeGM",
    type: "text",
    suffixInput: "$",
    validations: "number|positive",
    numberFormat: "$0,0",
    valid: true,
    disabled: true,
  },
  {
    name: "Store GM %",
    dataIndex: "storeGMPercent",
    type: "text",
    suffixInput: "%",
    validations: "number|min_value:0|max_value:100",
    numberFormat: "0.0%",
    valid: true,
    disabled: true,
  },
];

export const LIST_HEADER_ENTRY_PRICE = [
  "Sale Price",
  "Promo 1",
  "Promo 2",
  "Promo 3",
  "Promo 4",
  "Promo 5",
  "Promo 6",
  "Promo 7",
  "Promo 8",
  "Promo 9",
];

export const LIST_HEADER_METRIC = [...LIST_HEADER_ENTRY_PRICE, "Total"];

export const LIST_HEADER_PL = ["Ver. 1", "Ver. 2", "Ver. 3"];

export const LIST_ROW_NAME_ENTRY_METRICS = [
  {
    name: "NSV",
    dataIndex: "nsv",
    type: "dollar",
    numberFormat: "$0,0",
    numberFormat2: "$0,0.00",
  },
  {
    name: "CMA",
    dataIndex: "cma",
    type: "dollar",
    numberFormat: "$0,0.00",
    numberFormat2: "$0,0",
  },
  {
    name: "CMA %",
    dataIndex: "cmaPercent",
    type: "percent",
    numberFormat: "0,0.0%",
  },
  {
    name: "RSV",
    dataIndex: "rsv",
    type: "dollar",
    numberFormat: "$0,0.00",
    numberFormat2: "$0,0",
  },
  {
    name: "Retailer Margin",
    dataIndex: "retailerMargin",
    type: "dollar",
    numberFormat: "$0,0.00",
    numberFormat2: "$0,0",
  },
  {
    name: "Retailer Margin %",
    dataIndex: "retailerMarginPercent",
    type: "percent",
    numberFormat: "0,0.0%",
  },
];

export const LIST_ROW_NAME_ENTRY_KH_PL = [
  {
    name: "Units",
    dataIndex: "unit",
    dataNextIndex: "unitPercent",
    isBold: true,
  },
  {
    name: "Cases",
    dataIndex: "cases",
    dataNextIndex: "casesPercent",
    isBold: true,
    noneBorder: true,
  },
  {
    name: "List Sales Value",
    dataIndex: "listSalesValue",
    dataNextIndex: "listSalesValuePercent",
    isBold: true,
  },
  {
    name: "Fixed Terms",
    dataIndex: "fixedTerms",
    dataNextIndex: "fixedTermsPercent",
    isBold: false,
  },
  {
    name: "Efficiencies",
    dataIndex: "efficiencies",
    dataNextIndex: "efficienciesPercent",
    isChild: true,
    isBold: false,
  },
  {
    name: "Rebates",
    dataIndex: "rebates",
    dataNextIndex: "rebatesPercent",
    isChild: true,
    isBold: false,
  },
  {
    name: "Other",
    dataIndex: "other",
    dataNextIndex: "otherPercent",
    isChild: true,
    isBold: false,
  },
  {
    name: "Growth Incentive",
    dataIndex: "growthIncentive",
    dataNextIndex: "growthIncentivePercent",
    isChild: true,
    isBold: false,
  },
  {
    name: "Volumetric Discounts",
    dataIndex: "volumetricDiscounts",
    dataNextIndex: "volumetricDiscountsPercent",
    isBold: false,
  },
  {
    name: "Promo Off Invoice Discounts",
    dataIndex: "promoOffInvoiceDiscounts",
    dataNextIndex: "promoOffInvoiceDiscountsPercent",
    isBold: false,
  },
  {
    name: "Off Invoice Discounts",
    dataIndex: "offInvoice",
    dataNextIndex: "offInvoicePercent",
    isChild: true,
    isBold: false,
  },
  {
    name: "Margin Support Off Invoice",
    dataIndex: "marginSupport",
    dataNextIndex: "marginSupportPercent",
    isChild: true,
    isBold: false,
  },
  {
    name: "Every Day Low Price Off Invoice ",
    dataIndex: "edlp",
    dataNextIndex: "edlpPercent",
    isChild: true,
    isBold: false,
  },
  {
    name: "Invoiced Sales",
    dataIndex: "invoicedSales",
    dataNextIndex: "invoicedSalesPercent",
    isBold: true,
  },
  {
    name: "Scan",
    dataIndex: "scan",
    dataNextIndex: "scanPercent",
    isBold: false,
  },
  {
    name: "Warehouse Withdrawl",
    dataIndex: "warehouseWithdraw",
    dataNextIndex: "warehouseWithdrawPercent",
    isBold: false,
  },
  {
    name: "Case Deal Deferred",
    dataIndex: "caseDeal",
    dataNextIndex: "caseDealPercent",
    isBold: false,
  },
  {
    name: "Co-op Add",
    dataIndex: "coopAdd",
    dataNextIndex: "coopAddPercent",
    isBold: false,
  },
  {
    name: "Co-Op Display",
    dataIndex: "coopDisplay",
    dataNextIndex: "coopDisplayPercent",
    isBold: false,
  },
  {
    name: "Total Trade Investment",
    dataIndex: "tti",
    dataNextIndex: "ttiPercent",
    isBold: true,
  },
  {
    name: "Net Sales Value (NSV)",
    dataIndex: "nsv",
    dataNextIndex: "nsvPercent",
    noneBorder: true,
    isBold: true,
  },
  {
    name: "Cost of Goods",
    dataIndex: "costOfGoods",
    dataNextIndex: "costOfGoodsPercent",
    isBold: false,
  },
  {
    name: "Contribution Margin (CMA)",
    dataIndex: "cma",
    dataNextIndex: "cmaPercent",
    noneBorder: true,
    isBold: true,
  },
];

export const LIST_ROW_NAME_ENTRY_RETAIL_PL = [
  {
    name: "Units",
    dataIndex: "unit",
    dataNextIndex: "unitPercent",
    isBold: true,
  },
  {
    name: "Cases",
    dataIndex: "cases",
    dataNextIndex: "casesPercent",
    isBold: true,
    noneBorder: true,
  },
  {
    name: "RRP Sales Value",
    dataIndex: "rrpSaleValue",
    dataNextIndex: "rrpSaleValuePercent",
    isBold: true,
  },
  {
    name: "Consumer Discount",
    dataIndex: "consumerDiscount",
    dataNextIndex: "consumerDiscountPercent",
    isBold: false,
  },
  {
    name: "KH Funded",
    dataIndex: "khFunded",
    dataNextIndex: "khFundedPercent",
    isChild: true,
    isBold: false,
  },
  {
    name: "Retailer Funded",
    dataIndex: "retailerFunded",
    dataNextIndex: "retailerFundedPercent",
    isChild: true,
    isBold: false,
  },
  {
    name: "none",
    dataIndex: "none",
    dataNextIndex: "none",
    isBold: false,
  },
  {
    name: "none",
    dataIndex: "none",
    dataNextIndex: "none",
    isBold: false,
  },
  {
    name: "Retail Sales Value",
    dataIndex: "retailSaleValue",
    dataNextIndex: "retailSaleValuePercent",
    isBold: true,
  },
  {
    name: "Cost of Goods",
    dataIndex: "costOfGoods2",
    dataNextIndex: "costOfGoods2Percent",
  },
  {
    name: "Invoiced Sales",
    dataIndex: "retailerInvoicedSales",
    dataNextIndex: "retailerInvoicedSalesPercent",
    isBold: false,
    isFirstChild: true,
  },
  {
    name: "Rebates",
    dataIndex: "retailerRebates",
    dataNextIndex: "retailerRebatesPercent",
    isBold: false,
    isFirstChild: true,
  },
  {
    name: "Other Items",
    dataIndex: "retailerOther",
    dataNextIndex: "retailerOtherPercent",
    isFirstChild: true,
    isBold: false,
  },
  {
    name: "Growth Incentive",
    dataIndex: "retailerGrowthIncentive",
    dataNextIndex: "retailerGrowthIncentivePercent",
    isFirstChild: true,
    isBold: false,
  },
  {
    name: "Scan",
    dataIndex: "retailerScan",
    dataNextIndex: "retailerScanPercent",
    isFirstChild: true,
    isBold: false,
  },
  {
    name: "Warehouse Withdrawl",
    dataIndex: "retailerWarehouseWithdraw",
    dataNextIndex: "retailerWarehouseWithdrawPercent",
    isFirstChild: true,
    isBold: false,
  },
  {
    name: "Case Deal Deferred",
    dataIndex: "retailerCaseDeal",
    dataNextIndex: "retailerCaseDealPercent",
    isFirstChild: true,
    isBold: false,
    multiplier: -1,
  },
  {
    name: "none",
    dataIndex: "none",
    dataNextIndex: "none",
    isBold: false,
  },
  {
    name: "none",
    dataIndex: "none",
    dataNextIndex: "none",
    isBold: false,
  },
  {
    name: "Gross Margin excl Co-Op",
    dataIndex: "gmec",
    dataNextIndex: "gmecPercent",
    isBold: true,
  },
  {
    name: "Co-op Add",
    dataIndex: "retailerCoopAdd",
    dataNextIndex: "retailerCoopAddPercent",
    isFirstChild: true,
    isBold: false,
  },
  {
    name: "Co-Op Display",
    dataIndex: "retailerCoopDisplay",
    dataNextIndex: "retailerCoopDisplayPercent",
    isFirstChild: true,
    isBold: false,
  },
  {
    name: "Gross Margin incl Co-Op",
    dataIndex: "gmic",
    dataNextIndex: "gmicPercent",
    isBold: true,
    noneBorder: true,
  },
];

export const LIST_COL_NAME_WEEKLY_PRICE = [
  {
    name: "Week",
    dataIndex: "startDay",
    defaultVisible: true,
    key: "startDay",
    width: 150,
  },
  {
    name: "Primary Plan - Promo",
    dataIndex: "tacticName",
    defaultVisible: true,
    key: "tacticName",
    parse: (value) => value || null,
    readonly: true,
    width: 100,
  },
  {
    name: "Primary Plan - Price",
    dataIndex: "seqNumber",
    defaultVisible: true,
    numberFormat: "$0,0.00",
    suffixInput: "$",
    valid: true,
    type: "select",
    dataSource: "primaryPrices",
    source: "seqNumber",
    sourceLabel: "price",
    validations: "required",
    key: "seqNumber",
    width: 100,
  },
  {
    name: "Online Plan - Promo",
    dataIndex: "tacticNameOnline",
    defaultVisible: true,
    key: "tacticNameOnline",
    parse: (value) => value || null,
    readonly: true,
    width: 100,
  },
  {
    name: "Online Plan - Price",
    dataIndex: "seqNumberOnline",
    defaultVisible: true,
    numberFormat: "$0,0.00",
    suffixInput: "$",
    valid: true,
    type: "select",
    dataSource: "onlinePrices",
    source: "seqNumber",
    sourceLabel: "price",
    key: "seqNumberOnline",
    width: 100,
  },
  {
    name: "Total Unit",
    dataIndex: "unit",
    defaultVisible: true,
    key: "unit",
    numberFormat: "0",
    validations: "positive",
    parse: (value, record) => (value && record.seqNumber !== 1 ? value : null),
    valid: true,
    width: 100,
  },
  {
    name: "Baseline (BY)",
    key: "baseline",
    dataIndex: "baseline",
    defaultVisible: true,
    numberFormat: "0,0",
    readonly: true,
    parse: (value) => (value ? numeral(value).format("0,0") : ""),
    width: 120,
  },
  {
    name: "Uplift",
    key: "uplift",
    dataIndex: "uplift",
    defaultVisible: true,
    hasExpandButton: true,
    numberFormat: "0,0",
    readonly: true,
    parse: (value, record) =>
      !record.baseline || [0, 1].includes(record.seqNumber) || !record.seqNumber
        ? ""
        : numeral(value).format("0,0"),
    width: 100,
  },
  {
    name: "Co-op",
    dataIndex: "coopDisplay",
    defaultVisible: true,
    numberFormat: "$0,0.0",
    suffixInput: "$",
    valid: true,
    type: "text",
    key: "coopDisplay",
    hasTooltip: true,
    width: 100,
  },
  {
    name: "Display",
    dataIndex: "primaryInstoreDisplayId",
    defaultVisible: true,
    numberFormat: "",
    valid: true,
    type: "select",
    dataSource: "instoreDisplays",
    source: "id",
    sourceLabel: "description",
    key: "primaryInstoreDisplayId",
    hasTooltip: true,
    width: 100,
  },
  {
    name: "Feature",
    dataIndex: "secondInstoreDisplayId",
    defaultVisible: true,
    numberFormat: "",
    valid: true,
    type: "select",
    dataSource: "instoreDisplays",
    source: "id",
    sourceLabel: "description",
    key: "secondInstoreDisplayId",
    hasTooltip: true,
    width: 100,
  },
  {
    name: "Catalogue",
    dataIndex: "thirdInstoreDisplayId",
    defaultVisible: true,
    numberFormat: "",
    valid: true,
    type: "select",
    dataSource: "instoreDisplays",
    source: "id",
    sourceLabel: "description",
    key: "thirdInstoreDisplayId",
    hasTooltip: true,
    width: 100,
  },
  {
    name: "Event",
    dataIndex: "eventId",
    defaultVisible: true,
    valid: true,
    type: "select",
    dataSource: "events",
    source: "id",
    sourceDescription: "description",
    sourceLabel: "description",
    key: "eventId",
    hasTooltip: true,
    width: 100,
  },
  {
    name: "Note",
    dataIndex: "note",
    defaultVisible: true,
    valid: true,
    key: "note",
    hasTooltip: true,
    width: 200,
  },
];

export const LIST_ROW_NAME_SUB_PANEL = [
  {
    name: "IRI Retail Price",
    dataIndex: "iriRetailPrice",
    valid: true,
    // required: true,
    type: "text",
    key: "iriRetailPrice",
  },
  {
    name: "IRI Units",
    dataIndex: "iriUnits",
    validations: "integer|positive|not_equal:0",
    numberFormat: "0,0",
    valid: true,
    // required: true,
    type: "text",
    key: "iriUnits",
  },
  {
    name: "Volume Variance",
    dataIndex: "volumeVariance",
    validations: "integer|not_equal:0",
    numberFormat: "0,0",
    valid: true,
    // required: true,
    type: "text",
    key: "volumeVariance",
  },
];
