export const FREQUENCY_CHECK_GREEN_CODE = 1;
export const FREQUENCY_CHECK_ORANGE_CODE = 2;
export const FREQUENCY_CHECK_RED_CODE = 3;

export const FREQUENCY_CHECK_GREEN_COLOR = "#15b982";
export const FREQUENCY_CHECK_ORANGE_COLOR = "#fa8c16";
export const FREQUENCY_CHECK_RED_COLOR = "#f5222d";

export const FREQUENCY_CHECK_GREEN_ICON = "check-circle";
export const FREQUENCY_CHECK_ORANGE_ICON = "info-circle";
export const FREQUENCY_CHECK_RED_ICON = "close-circle";

export const FREQUENCY_CHECK = {
  [FREQUENCY_CHECK_GREEN_CODE]: {
    color: FREQUENCY_CHECK_GREEN_COLOR,
    icon: FREQUENCY_CHECK_GREEN_ICON,
  },
  [FREQUENCY_CHECK_ORANGE_CODE]: {
    color: FREQUENCY_CHECK_ORANGE_COLOR,
    icon: FREQUENCY_CHECK_ORANGE_ICON,
  },
  [FREQUENCY_CHECK_RED_CODE]: {
    color: FREQUENCY_CHECK_RED_COLOR,
    icon: FREQUENCY_CHECK_RED_ICON,
  },
};
